server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      maxIdleTimeMin: ${MONGO_MAX_IDLE_TIME_MIN:15}
      maxSize: ${MONGO_MAX_SIZE:100}
      minSize: ${MONGO_MIN_SIZE:10}
      username: self_user
      password: self_pwd
      database: self-db
      host: mongo-db
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret

api:
  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfServiceUrl: http://localhost:8080
    license: License
    licenseUrl: http://localhost:8080
    contact:
      name: Contact
      url: http://localhost:8080
      email: me@mail.com

springdoc:
  use-management-port: true
  show-actuator: true

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: info, health, metrics, openapi, swagger-ui
