version: '3.9'
services:
  mongo-db:
    container_name: mongo-db
    image: 'mongo:latest'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=self-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
    - '27017:27017'

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    depends_on:
      - mongo-db
    ports:
      - '8888:8081'

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:latest'
    restart: unless-stopped
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'

  self-improvement-service:
    container_name: self-improvement-service
    image: 'self-improvement-app-image:latest'
    restart: unless-stopped
    ports:
    - '8080:8080'
    depends_on:
      - mongo-db