openapi: "3.0.3"
info:
  title: "self_improvement API"
  description: "self_improvement API"
  version: "1.0.0"
servers:
  - url: "https://self_improvement"
paths:
  /pets:
    get:
      summary: "GET pets"
      operationId: "getPets"
      responses:
        "200":
          description: "OK"
          content:
            #            text/event-stream:
            application/x-ndjson:
              schema:
                $ref: "#/components/schemas/InitFlowResponse"
    post:
      summary: "POST pet"
      operationId: "postPet"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/InitFlowResponse"

components:
  schemas:
    InitFlowResponse:
      type: "object"
      properties:
        data:
          $ref: "#/components/schemas/Data"
        errorData:
          $ref: "#/components/schemas/ErrorData"
    Data:
      type: "object"
      properties:
        pets:
          items:
            $ref: "#/components/schemas/Pet"
        pet:
          $ref: "#/components/schemas/Pet"
    ErrorData:
      type: "object"
    Pet:
      type: "object"
      properties:
        name:
          type: "string"