version: '3.9'
services:
  self-improvement-service:
    container_name: self-improvement-service
    image: 'self-improvement-app-image:latest'
    restart: unless-stopped
    ports:
      - '8080:8080'
